version: '3.3'
services:
    tlxde:
        ports:
            - '6081:443'
        volumes:
            - '${PWD}/disk:/home/telegram/Documents'
            - '${PWD}/Telegram Desktop:/home/telegram/Downloads/Telegram Desktop'
            - '${PWD}/ssl:/etc/nginx/ssl'
            - '${PWD}/tdata:/home/telegram/.local/share/TelegramDesktop'
            - '/dev/shm:/dev/shm'
        build:
            context: .
            args:
                USER: telegram
        environment:
            - USER=telegram
            - PASSWORD=telegram
            - SSL_PORT=443
            - HTTP_PASSWORD=telegram
