version: '3.3'
services:
    signal:
        ports:
            - '6081:443'
        volumes:
            - '${PWD}/documents:/home/signal/Documents'
            - '${PWD}/downloads:/home/signal/Downloads'
            - '${PWD}/ssl:/etc/nginx/ssl'
            - '${PWD}/signal_data:/home/signal/.config/Signal'
            - '/dev/shm:/dev/shm'
        build:
            context: .
            args:
                USER: signal
        environment:
            - USER=signal
            - PASSWORD=signal
            - SSL_PORT=443
            - HTTP_PASSWORD=signal
